### ISSUE TITLE
Bug ?

### ISSUE THREAD

**Issue by Coolmicro** [DocMarty84/oomusic#5]
Bonjour,
Après avoir compris, ce qui n'était pas évident, qu'il me fallait créer un utilisateur Linux identique à l'utilisateur PostgreSQL créé (UserKoozic pour l'exemple ci-dessous), j'ai lancé la commande :
sudo -u UserKoozic ./odoo-bin -i oomusic -d koozic --without-demo=all --stop-after-init
Apparemment, tout était OK.
Mais lorsque je lance ensuite la commande :
sudo -u UserKoozic ./odoo-bin
j'obtiens des erreurs (copie écran ci-dessous) et une interface assez "destroy" bien différente de celle de la demo.
![erreurs](https://cloud.githubusercontent.com/assets/16964969/22409843/a3cb2278-e690-11e6-9071-a0c0cbb10360.jpg)
Nota : je suis sous Debian 8.5 à jour, serveur web nginx, toutes les dépendances indiquées installées.
Merci d'avance
Cordialement

**Comment by nicolasmartinelli** [comment]
Salut,

Cela est dû à une dépendance manquante : node-less

As-tu bien suivi la partie "Ubuntu et Debian" du guide d'installation
https://koozic.net/installation/ ? L'astuce de l'utilisateur pour Postgres
y est indiquée, ainsi que toutes les dépendances nécessaires. Il te faudra
aussi installer ffmpeg.

**Comment by nicolasmartinelli** [comment]
Sur une Debian Jessie fraichement installée, voilà étape par étape ce que j'ai fait (l'utilisateur est koozic):

```shell
su -
adduser koozic
echo "deb http://ftp.debian.org/debian jessie-backports main" >> /etc/apt/sources.list
apt update
apt install adduser node-less postgresql-client python python-dateutil python-decorator\
    python-docutils python-feedparser python-imaging python-jinja2 python-ldap python-libxslt1\
    python-lxml python-mako python-mock python-openid python-passlib python-psutil python-psycopg2\
    python-pybabel python-pychart python-pydot python-pyparsing python-pypdf python-reportlab\
    python-requests python-suds python-tz python-vatnumber python-vobject python-werkzeug\
    python-xlsxwriter python-xlwt python-yaml postgresql python-mutagen ffmpeg
su - postgres -c "createuser -s koozic"

su - koozic
mkdir src
cd src
wget https://koozic.net/releases/koozic-v0.3.0.zip
unzip koozic-v0.3.0.zip
cd koozic
./odoo-bin -i oomusic -d koozic --without-demo=all --stop-after-init
./odoo.bin
```

**Comment by Coolmicro** [comment]
Salut Nicolas,
Merci pour ta réponse.
Le problème, c'est que j'avais suivi toutes les instructions (même si au 
début je n'avais pas compris le coup de l'utilisateur :D)
J'ai relativement l'habitude d'installer et maintenir des tas de trucs 
sur mon serveur, depuis une dizaine d'années, de nextcloud à cherrymusic 
en passant par piwigo et autres. J'ai pris l'habitude d'être 
précautionneux, de tout noter, et de bien étudier avant de me lancer
J'avais installé toutes les dépendances, node-less compris, c'est le 1er 
truc que j'ai vérifié au vu du message.
Mais j'ai fini par comprendre...
En fait, j'avais installé node.js, il y a un moment, pour des tests, et 
j'avais oublié. A l'époque, j'avais effectué l'install à partir d'un 
dépôt spécifique :  https://deb.nodesource.com/node_6.x jessie main
C'était lui le fautif. J'ai enlevé le dépôt, désinstallé node.js et 
node-less, fait l'update et réinstallé, et plus d'erreur...
Il ne me reste qu'à découvrir et tester... (mais d'abord, il faut 
scanner 160 Go de musique :D)
Si je suis séduit par l'utilisation, je mettrai un sous-domaine Nginx en 
https (pour le moment, c'est bêtement adresseip:port). Je regarderai 
aussi si je ne peux pas utiliser systemd (à moins que tu aies déjà testé ?)
Je te tiendrai au courant (peut-être pas tout de suite, j'ai une tonne 
de choses à faire sur un autre serveur)
Cordialement
Michel (Coolmicro)

**Comment by Coolmicro** [comment]
Salut Nicolas,

J'ai effectué tous les tests de l'API Subsonic avec les 3 applis Android
que tu recommandais (les seules correctement notées d'ailleurs sur le
store). Je passe sur l'appli officielle trop pauvre pour en parler, ce sont
les 2 autres qui m'intéressent.
Je te dis uniquement ce qui ne va pas, mais je tiens à dire que globalement
ça fonctionne... :D et te remercier encore pour ton boulot.

Avec ces 2 applis, les genres ne sont pas du tout gérés (alors que c'est
parfait sur l'interface web) :
* Pour dsub, quand on clique sur n'importe quel genre, on arrive sur une
liste d'albums qui correspondent en fait au 1er dossier alphabétique de ma
musique (ou le 1er genre ? j'utilise le même nom pour ce 1er dossier et le
1er genre)
. Idem pour les classements par années, mais je ne sais pas si c'est censé
être géré.
* Pour Ultrasonic, on arrive sur les morceaux de musique du 1er album du
genre choisi
Bref, non utilisable dans les 2 cas, ce qui est dommage. Je ne sais pas si
tu peux faire quelque chose.

Pour la recherche, je teste toujours avec le mot melody, car j'ai
artiste/album/titres qui contiennent ce mot.Pour dsub et Ultrasonic, on
obtient un rectangle noir sous la rubrique artiste après une recherche sur
"melody", mais en cliquant sur ce rectangle noir, on aboutit bien à Melody
Gardot... Comme c'est commun au 2 clients Android, je pense qu'il s'agit
d'un petit bug de Koozic.

Et je termine par 2 petits trucs qui concernent cette fois l'interface web
de Koozic :

* J'ai crée un autre utilisateur, sans droits d'administration. Le problème
c'est que chemin vers le dossier musique de l'admin ne peut être répercuté
vers un autre utilisateur. SI on ajoute le même chemin chez l'utilisateur,
on se retrouve avec 2 fois le même chemin chez l'admin

* Il est assez délicat de se déconnecter. On obtient ce message :
Traceback (most recent call last):
  File "/home/var/www/koozic/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/var/www/koozic/odoo/addons/base/ir/ir_http.py", line 184, in
_dispatch
    auth_method = cls._authenticate(func.routing["auth"])
  File "/home/var/www/koozic/odoo/addons/base/ir/ir_http.py", line 112, in
_authenticate
    getattr(cls, "_auth_method_%s" % auth_method)()
  File "/home/var/www/koozic/odoo/addons/base/ir/ir_http.py", line 85, in
_auth_method_user
    raise http.SessionExpiredException("Session expired")
SessionExpiredException: Session expired

Et ce message persiste même quand on veut se reconnecter. Il faut supprimer
le cookie pour pouvoir se reconnecter. perso, cela me gêne pas, mais j'ai
préféré te le signaler.

Bien cordialement
Michel



2017-01-30 8:56 GMT+01:00 nicolasmartinelli <notifications@github.com>:

**Comment by nicolasmartinelli** [comment]
Salut,

Merci pour ton retour. Concernant nginx, il y a un exemple de config [ici](https://github.com/nicolasmartinelli/koozic/blob/master/extra/doc/nginx_ssl_config). C'est ce que j'utilise, et aucun souci. Je vais travailler sur une config systemd d'ici peu, mais a priori ça ne doit pas être très compliqué à écrire.

Pour le genre et la recherche, as-tu configuré les applis pour utiliser les tags? Par exemple, dans DSub, ça se fait dans la configuration du serveur ("Naviguer via les tags").

Pour la petite histoire, Subsonic a commencé à supporter les tags en v4.7. Auparavant, l'artiste ou l'album étaient déterminés suivant la hiérarchie de répertoire. Pour faire court, c'est une horreur à implémenter, et cela pourrait expliquer les incohérences que tu retrouves dans les recherches. Je viens de tester avec le serveur de démo, et si je désactive la navigation par tags sur DSub, la recherche et le classement par genre donnent des résultats... mauvais :-) Si la navigation par tags est activée, c'est nickel.

Tu peux toujours essayer avec le serveur de demo (url: http://demo.koozic.net:8069, login et pass: demo). Si la navigation par genre et la recherche fonctionnent normalement sur le serveur de démo et pas avec ton serveur, on essaiera de trouver le souci.

> J'ai crée un autre utilisateur, sans droits d'administration. Le problème c'est que chemin vers le dossier musique de l'admin ne peut être répercuté vers un autre utilisateur. SI on ajoute le même chemin chez l'utilisateur, on se retrouve avec 2 fois le même chemin chez l'admin

Oui, ça c'est inhérent à Odoo (le logiciel de base sur lequel je me suis greffé). L'administrateur (en fait, l'équivalent de root) a accès à tout, ce qui permet de gérer les données de tous les autres utilisateurs. Si tu as un système avec plusieurs utilisateurs, mieux vaut avoir un administrateur que tu n'utilises que pour la configuration, et d'autres utilisateurs pour lesquels tu ajoutes des dossiers musicaux à scanner. Un peu comme sous Linux, en somme ;-)

> Il est assez délicat de se déconnecter. On obtient ce message :

C'est probablement parce que tu étais connecté avec 2 utilisateurs différents sur le même navigateur. Effectivement, un nettoyage des cookies doit régler le soucis.

**Comment by Coolmicro** [comment]
Salut,
Pour nginx, j'utilise une config un chouïa différente (je mets la même 
sur tous mes sites => grade A+ mais cela revient au même pour un site de 
musique :D)
Pour systemd, j'ai laissé ma config sur 
http://15minutesoffame.be/nico/blog2/index.php?article27/koozic-sortie-de-la-v0-3-0 
: tu me diras si tu en fais une autre (je ne suis pas du tout un 
spécialiste de systemd...)
Merci pour les infos sur subsonic, j'ai activé la navigation par tag, et 
j'ai fait les tests avec ton serveur de demo (résultats identiques au 
mien). Je vais détailler ce qui fait que cette navigation par tags ne 
peut me convenir, non que tu puisses y faire quelque chose (j'ai compris 
que c'est lié à Subsonic puisque l'interface web de Koozic ne présentent 
pas les problèmes que je vais évoquer), simplement pour ton information.

Commençons par dsub :
Bibliothèque : Avec la navigation par tag, j'obtiens la liste de tous 
les auteurs par ordre alphabétique : inutilisable avec + de 2000 albums. 
Comme l'organisation physique de mes dossiers est : genre > artiste > 
album > morceaux, il vaut mieux que j'ai cette organisation pour la biblio.
Accueil / Genres : les genres fonctionnent effectivement, mais à 
l'intérieur des genres, les albums en vrac : je te dis pas quand il y a 
plusieurs centaines d'albums dans un genre :D Je suppose que c'est la 
manière de faire de Subsonic (il me semble que j'avais déjà vu un truc 
de ce genre quand j'avais testé ampache...)
Du coup, je décoche la navigation par tags qui n'est pas utilisable avec 
une grosse biblio et j'abandonne l'idée d'utiliser les genres (pour 
comprendre, mes genres sont plus "fins" que mes dossiers, par exemple 
j'ai un gros dossier physique classique, avec des genres classique, 
classique vocal, opéra, opérette dedans)
A noter que le bug sur la recherche déjà signalé (les artistes 
n'apparaissent pas), et propre à Koozic (pas de bug sur le serveur demo 
Subsonic), demeure même si on coche la navigation par tags.

Ultrasonic :
Le bug évoqué pour les genres (on accède directement et uniquement à un 
album du genre) demeure avec la navigation par tags, donc c'est lié à 
Ultrasonic.
Pour la bibliothèque et le reste, idem dsub.

Merci pour l'explication sur l'administrateur, les utilisateurs et les 
chemins vers la musique

Pour ce que j'ai décrit concernant la déconnexion, je n'étais pas 
connecté avec 2 utilisateurs sur le même navigateur, mais je confirme 
qu'il suffit d'enlever les cookies pour régler le problème.

Cordialement

Michel

**Comment by nicolasmartinelli** [comment]
> Pour systemd, j'ai laissé ma config sur http://15minutesoffame.be/nico/blog2/index.php?article27/koozic-sortie-de-la-v0-3-0 : tu me diras si tu en fais une autre (je ne suis pas du tout un spécialiste de systemd...)

Merci, je vais jeter un œil à ça ce week-end.

> les genres fonctionnent effectivement, mais à l'intérieur des genres, les albums en vrac : je te dis pas quand il y a plusieurs centaines d'albums dans un genre :D Je suppose que c'est la manière de faire de Subsonic 

Oui, KooZic ou Subsonic envoient la liste des albums liés à un genre. C'est voulu, et effectivement ça envoie la liste d'albums en vrac.

> A noter que le bug sur la recherche déjà signalé (les artistes n'apparaissent pas), et propre à Koozic (pas de bug sur le serveur demo Subsonic), demeure même si on coche la navigation par tags.

OK, c'est réglé sur la [v0.3.1](https://koozic.net/releases/koozic-v0.3.1.zip), avec https://github.com/nicolasmartinelli/oomusic/commit/9c56a578b96f15b0f195a0bd070451a93c46cf32. Il suffit de mettre à jour les sources (supprimer les sources existantes et dézipper les nouvelles), et relancer le serveur.

> Pour ce que j'ai décrit concernant la déconnexion, je n'étais pas connecté avec 2 utilisateurs sur le même navigateur, mais je confirme qu'il suffit d'enlever les cookies pour régler le problème.

Ouais, j'ai vu passer ce soucis dans les bugs d'Odoo, ça sera réglé un jour ou l'autre (le temps que ça soit réglé sur Odoo, puis que je répercute ça sur KooZic, ce que je ne fais pas forcément régulièrement).

**Comment by nicolasmartinelli** [comment]
Au cas où: http://localhost:8069/web/database/manager (une note a été ajoutée à ce sujet à https://koozic.net/installation/)

**Comment by Coolmicro** [comment]
Salut Nicolas,
Merci pour tes réponses, je vais installer la nouvelle version.
Pour /web/database/manager  j'avais déjà vu (je ne sais plus comment, je 
crois que j'en ai profité pour mettre un mot de passe maître sur la base)
Bonne fin de semaine
Michel
